name: kingfisher
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# - eggshell
# analytic
- python=2.7 # SNAP toolbox support only 2.7 3.3 3.4 
- numpy
# visualisation
- cartopy
# EO Data
- gdal
- rasterio
- pip:
   - sentinelsat
   - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
