name: kingfisher
channels:
- birdhouse
- conda-forge
- defaults
dependencies:
- pywps=4.1
- jinja2
- click
- psutil
# - eggshell
# analytic
- python=2.7
- numpy
# visualisation
- cartopy
# EO Data
- gdal
- rasterio
- pip:
   - sentinelsat
   - -e git+https://github.com/bird-house/eggshell.git#egg=eggshell
